# Generated by Django 5.0.3 on 2024-03-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_options_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='views',
        ),
    ]
