# Generated by Django 5.0.3 on 2024-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
