# Generated by Django 5.0.3 on 2024-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_emailsubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubs',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailsubs',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
