# Generated by Django 5.0.3 on 2024-03-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comments_options_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
